name: Deploy
on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        required: true
        description: "Nome do ambiente que sera realizado o deploy"
      host_name:
        type: string
        description: "Host do ambiente que sera realizado o deploy"
      manifests:
        required: true
        type: string
        description: "Host do ambiente que sera realizado o deploy"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.host_name && format('http://{0}', inputs.host_name) || '' }}
    steps:
      - name: "Obtendo arquivos do projeto"
        uses: actions/checkout@v4
        
      - name: "Configurando contexto/autenticacao do k8s"
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Atualizar host name
        working-directory: ./src/ManifestsK8s/boards-k8s/deploy
        if: ${{ inputs.host_name }}
        run: |
          sed -i "s|host: \[host-name\]|host: ${{ inputs.host_name }}|" ./ingress.yaml
      
      - name: "Execução dos manifestos (${{ inputs.environment_name }})" 
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{ inputs.environment_name }}
          manifests: ${{ inputs.manifests }}
          images: |
            fspelling/boardk8s:v${{ github.run_number }}
